name: Update Huawei Bisheng

on:
  schedule:
    - cron: 0 15 * * 1-5
  workflow_dispatch:

jobs:
  run:
    name: "Run Java Migration for Huawei Bisheng"
    strategy:
      fail-fast: false
      matrix:
        java-version: [ 8, 11, 17 ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Java 21
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: 21
          cache: 'maven'
      - name: Run Huawei Bisheng
        run: ./mvnw spring-boot:run -Dspring-boot.run.arguments="--foojay.java.distribution=bisheng --foojay.distribution.version=${{ matrix.java-version }} --foojay.java.release-status=ga"
        env:
          SDKMAN_RELEASE_CONSUMER_KEY: ${{ secrets.CONSUMER_KEY }}
          SDKMAN_RELEASE_CONSUMER_TOKEN: ${{ secrets.CONSUMER_TOKEN }}
